services:
    nti.sync.doctrine.listener:
        class: NTI\SyncBundle\EventListener\DoctrineEventSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    nti.sync:
            class: NTI\SyncBundle\Service\SyncService
            arguments: ["@service_container"]
            public: true